# Generated by Django 4.2.4 on 2023-08-08 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('revenue', '0002_taxpayer_alter_revenuecategory_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='revenuecategory',
            name='parent_category',
        ),
    ]
