# Generated by Django 4.2.4 on 2023-08-08 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('revenue', '0003_remove_revenuecategory_parent_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='RevenueTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('note', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('revenue_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='revenue.revenuesource')),
                ('tax_payer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='revenue.taxpayer')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
