# Generated by Django 4.2.4 on 2023-08-08 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revenue', '0004_revenuetransaction'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='revenuetransaction',
            options={'ordering': ['-created'], 'verbose_name_plural': 'Revenue Transactions'},
        ),
        migrations.AlterField(
            model_name='taxpayer',
            name='address',
            field=models.CharField(max_length=255),
        ),
    ]
