# Generated by Django 4.2.4 on 2023-08-10 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revenue', '0006_alter_revenuecategory_name_alter_revenuesource_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='revenuetransaction',
            name='created',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='taxpayer',
            name='name',
            field=models.CharField(help_text='Business name or Personal name', max_length=200, unique=True),
        ),
    ]
