# Generated by Django 4.2.4 on 2023-08-11 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revenue', '0007_alter_revenuetransaction_created_alter_taxpayer_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxpayer',
            name='created',
            field=models.DateTimeField(),
        ),
    ]
